// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/memory_service.proto

package memoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStructuredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStructuredRequest) Reset() {
	*x = GetStructuredRequest{}
	mi := &file_proto_memory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStructuredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStructuredRequest) ProtoMessage() {}

func (x *GetStructuredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStructuredRequest.ProtoReflect.Descriptor instead.
func (*GetStructuredRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetStructuredRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStructuredResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw JSON string or serialized row from persistence layer.
	JsonValue     string `protobuf:"bytes,1,opt,name=json_value,json=jsonValue,proto3" json:"json_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStructuredResponse) Reset() {
	*x = GetStructuredResponse{}
	mi := &file_proto_memory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStructuredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStructuredResponse) ProtoMessage() {}

func (x *GetStructuredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStructuredResponse.ProtoReflect.Descriptor instead.
func (*GetStructuredResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetStructuredResponse) GetJsonValue() string {
	if x != nil {
		return x.JsonValue
	}
	return ""
}

type StoreStructuredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreStructuredRequest) Reset() {
	*x = StoreStructuredRequest{}
	mi := &file_proto_memory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreStructuredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStructuredRequest) ProtoMessage() {}

func (x *StoreStructuredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStructuredRequest.ProtoReflect.Descriptor instead.
func (*StoreStructuredRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{2}
}

func (x *StoreStructuredRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreStructuredRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StoreStructuredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreStructuredResponse) Reset() {
	*x = StoreStructuredResponse{}
	mi := &file_proto_memory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreStructuredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStructuredResponse) ProtoMessage() {}

func (x *StoreStructuredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStructuredResponse.ProtoReflect.Descriptor instead.
func (*StoreStructuredResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{3}
}

type StoreUnstructuredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                             // optional textual content or JSON
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`                      // embedding
	IndexGlobal   bool                   `protobuf:"varint,4,opt,name=index_global,json=indexGlobal,proto3" json:"index_global,omitempty"` // whether to index in global store
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreUnstructuredRequest) Reset() {
	*x = StoreUnstructuredRequest{}
	mi := &file_proto_memory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreUnstructuredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUnstructuredRequest) ProtoMessage() {}

func (x *StoreUnstructuredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUnstructuredRequest.ProtoReflect.Descriptor instead.
func (*StoreUnstructuredRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{4}
}

func (x *StoreUnstructuredRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreUnstructuredRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreUnstructuredRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *StoreUnstructuredRequest) GetIndexGlobal() bool {
	if x != nil {
		return x.IndexGlobal
	}
	return false
}

type StoreUnstructuredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreUnstructuredResponse) Reset() {
	*x = StoreUnstructuredResponse{}
	mi := &file_proto_memory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreUnstructuredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUnstructuredResponse) ProtoMessage() {}

func (x *StoreUnstructuredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUnstructuredResponse.ProtoReflect.Descriptor instead.
func (*StoreUnstructuredResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{5}
}

type SearchUnstructuredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`            // "LOCAL" or "GLOBAL"
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"` // query embedding
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUnstructuredRequest) Reset() {
	*x = SearchUnstructuredRequest{}
	mi := &file_proto_memory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUnstructuredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUnstructuredRequest) ProtoMessage() {}

func (x *SearchUnstructuredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUnstructuredRequest.ProtoReflect.Descriptor instead.
func (*SearchUnstructuredRequest) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchUnstructuredRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SearchUnstructuredRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchUnstructuredRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchUnstructuredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Scores        []float32              `protobuf:"fixed32,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUnstructuredResponse) Reset() {
	*x = SearchUnstructuredResponse{}
	mi := &file_proto_memory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUnstructuredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUnstructuredResponse) ProtoMessage() {}

func (x *SearchUnstructuredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUnstructuredResponse.ProtoReflect.Descriptor instead.
func (*SearchUnstructuredResponse) Descriptor() ([]byte, []int) {
	return file_proto_memory_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchUnstructuredResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SearchUnstructuredResponse) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_proto_memory_service_proto protoreflect.FileDescriptor

const file_proto_memory_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/memory_service.proto\x12\tmemory.v1\"(\n" +
	"\x14GetStructuredRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\x15GetStructuredResponse\x12\x1d\n" +
	"\n" +
	"json_value\x18\x01 \x01(\tR\tjsonValue\"@\n" +
	"\x16StoreStructuredRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x19\n" +
	"\x17StoreStructuredResponse\"\x7f\n" +
	"\x18StoreUnstructuredRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12!\n" +
	"\findex_global\x18\x04 \x01(\bR\vindexGlobal\"\x1b\n" +
	"\x19StoreUnstructuredResponse\"^\n" +
	"\x19SearchUnstructuredRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"F\n" +
	"\x1aSearchUnstructuredResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x16\n" +
	"\x06scores\x18\x02 \x03(\x02R\x06scores2\x88\x03\n" +
	"\rMemoryService\x12T\n" +
	"\rGetStructured\x12\x1f.memory.v1.GetStructuredRequest\x1a .memory.v1.GetStructuredResponse\"\x00\x12Z\n" +
	"\x0fStoreStructured\x12!.memory.v1.StoreStructuredRequest\x1a\".memory.v1.StoreStructuredResponse\"\x00\x12`\n" +
	"\x11StoreUnstructured\x12#.memory.v1.StoreUnstructuredRequest\x1a$.memory.v1.StoreUnstructuredResponse\"\x00\x12c\n" +
	"\x12SearchUnstructured\x12$.memory.v1.SearchUnstructuredRequest\x1a%.memory.v1.SearchUnstructuredResponse\"\x00B\x17Z\x15api/memoryv1;memoryv1b\x06proto3"

var (
	file_proto_memory_service_proto_rawDescOnce sync.Once
	file_proto_memory_service_proto_rawDescData []byte
)

func file_proto_memory_service_proto_rawDescGZIP() []byte {
	file_proto_memory_service_proto_rawDescOnce.Do(func() {
		file_proto_memory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_memory_service_proto_rawDesc), len(file_proto_memory_service_proto_rawDesc)))
	})
	return file_proto_memory_service_proto_rawDescData
}

var file_proto_memory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_memory_service_proto_goTypes = []any{
	(*GetStructuredRequest)(nil),       // 0: memory.v1.GetStructuredRequest
	(*GetStructuredResponse)(nil),      // 1: memory.v1.GetStructuredResponse
	(*StoreStructuredRequest)(nil),     // 2: memory.v1.StoreStructuredRequest
	(*StoreStructuredResponse)(nil),    // 3: memory.v1.StoreStructuredResponse
	(*StoreUnstructuredRequest)(nil),   // 4: memory.v1.StoreUnstructuredRequest
	(*StoreUnstructuredResponse)(nil),  // 5: memory.v1.StoreUnstructuredResponse
	(*SearchUnstructuredRequest)(nil),  // 6: memory.v1.SearchUnstructuredRequest
	(*SearchUnstructuredResponse)(nil), // 7: memory.v1.SearchUnstructuredResponse
}
var file_proto_memory_service_proto_depIdxs = []int32{
	0, // 0: memory.v1.MemoryService.GetStructured:input_type -> memory.v1.GetStructuredRequest
	2, // 1: memory.v1.MemoryService.StoreStructured:input_type -> memory.v1.StoreStructuredRequest
	4, // 2: memory.v1.MemoryService.StoreUnstructured:input_type -> memory.v1.StoreUnstructuredRequest
	6, // 3: memory.v1.MemoryService.SearchUnstructured:input_type -> memory.v1.SearchUnstructuredRequest
	1, // 4: memory.v1.MemoryService.GetStructured:output_type -> memory.v1.GetStructuredResponse
	3, // 5: memory.v1.MemoryService.StoreStructured:output_type -> memory.v1.StoreStructuredResponse
	5, // 6: memory.v1.MemoryService.StoreUnstructured:output_type -> memory.v1.StoreUnstructuredResponse
	7, // 7: memory.v1.MemoryService.SearchUnstructured:output_type -> memory.v1.SearchUnstructuredResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_memory_service_proto_init() }
func file_proto_memory_service_proto_init() {
	if File_proto_memory_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_memory_service_proto_rawDesc), len(file_proto_memory_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_memory_service_proto_goTypes,
		DependencyIndexes: file_proto_memory_service_proto_depIdxs,
		MessageInfos:      file_proto_memory_service_proto_msgTypes,
	}.Build()
	File_proto_memory_service_proto = out.File
	file_proto_memory_service_proto_goTypes = nil
	file_proto_memory_service_proto_depIdxs = nil
}
