// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/memory_service.proto

package memoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_GetStructured_FullMethodName      = "/memory.v1.MemoryService/GetStructured"
	MemoryService_StoreStructured_FullMethodName    = "/memory.v1.MemoryService/StoreStructured"
	MemoryService_StoreUnstructured_FullMethodName  = "/memory.v1.MemoryService/StoreUnstructured"
	MemoryService_SearchUnstructured_FullMethodName = "/memory.v1.MemoryService/SearchUnstructured"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryServiceClient interface {
	// Structured key-value read.
	GetStructured(ctx context.Context, in *GetStructuredRequest, opts ...grpc.CallOption) (*GetStructuredResponse, error)
	// Structured key-value write.
	StoreStructured(ctx context.Context, in *StoreStructuredRequest, opts ...grpc.CallOption) (*StoreStructuredResponse, error)
	// Unstructured store: content + embedding + optional global index.
	StoreUnstructured(ctx context.Context, in *StoreUnstructuredRequest, opts ...grpc.CallOption) (*StoreUnstructuredResponse, error)
	// Unstructured semantic search: scope = LOCAL or GLOBAL.
	SearchUnstructured(ctx context.Context, in *SearchUnstructuredRequest, opts ...grpc.CallOption) (*SearchUnstructuredResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) GetStructured(ctx context.Context, in *GetStructuredRequest, opts ...grpc.CallOption) (*GetStructuredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStructuredResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetStructured_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) StoreStructured(ctx context.Context, in *StoreStructuredRequest, opts ...grpc.CallOption) (*StoreStructuredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreStructuredResponse)
	err := c.cc.Invoke(ctx, MemoryService_StoreStructured_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) StoreUnstructured(ctx context.Context, in *StoreUnstructuredRequest, opts ...grpc.CallOption) (*StoreUnstructuredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreUnstructuredResponse)
	err := c.cc.Invoke(ctx, MemoryService_StoreUnstructured_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SearchUnstructured(ctx context.Context, in *SearchUnstructuredRequest, opts ...grpc.CallOption) (*SearchUnstructuredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUnstructuredResponse)
	err := c.cc.Invoke(ctx, MemoryService_SearchUnstructured_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
type MemoryServiceServer interface {
	// Structured key-value read.
	GetStructured(context.Context, *GetStructuredRequest) (*GetStructuredResponse, error)
	// Structured key-value write.
	StoreStructured(context.Context, *StoreStructuredRequest) (*StoreStructuredResponse, error)
	// Unstructured store: content + embedding + optional global index.
	StoreUnstructured(context.Context, *StoreUnstructuredRequest) (*StoreUnstructuredResponse, error)
	// Unstructured semantic search: scope = LOCAL or GLOBAL.
	SearchUnstructured(context.Context, *SearchUnstructuredRequest) (*SearchUnstructuredResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) GetStructured(context.Context, *GetStructuredRequest) (*GetStructuredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStructured not implemented")
}
func (UnimplementedMemoryServiceServer) StoreStructured(context.Context, *StoreStructuredRequest) (*StoreStructuredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreStructured not implemented")
}
func (UnimplementedMemoryServiceServer) StoreUnstructured(context.Context, *StoreUnstructuredRequest) (*StoreUnstructuredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreUnstructured not implemented")
}
func (UnimplementedMemoryServiceServer) SearchUnstructured(context.Context, *SearchUnstructuredRequest) (*SearchUnstructuredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUnstructured not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_GetStructured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStructuredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetStructured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetStructured_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetStructured(ctx, req.(*GetStructuredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_StoreStructured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreStructuredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).StoreStructured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_StoreStructured_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).StoreStructured(ctx, req.(*StoreStructuredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_StoreUnstructured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUnstructuredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).StoreUnstructured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_StoreUnstructured_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).StoreUnstructured(ctx, req.(*StoreUnstructuredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SearchUnstructured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUnstructuredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SearchUnstructured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SearchUnstructured_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SearchUnstructured(ctx, req.(*SearchUnstructuredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memory.v1.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStructured",
			Handler:    _MemoryService_GetStructured_Handler,
		},
		{
			MethodName: "StoreStructured",
			Handler:    _MemoryService_StoreStructured_Handler,
		},
		{
			MethodName: "StoreUnstructured",
			Handler:    _MemoryService_StoreUnstructured_Handler,
		},
		{
			MethodName: "SearchUnstructured",
			Handler:    _MemoryService_SearchUnstructured_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/memory_service.proto",
}
